//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPLFantasy
{
    using System;
    using System.Collections.Generic;
    
    public partial class DreamTeamPlayer
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Team_id { get; set; }
        public int Points { get; set; }
        public Nullable<bool> IsGirlplayer { get; set; }
        public int runsScored { get; set; }
        public int noOfFours { get; set; }
        public int noOfSixes { get; set; }
        public int noOfwickets { get; set; }
        public int maidenOver { get; set; }
        public int noOfCatches { get; set; }
        public int stumping { get; set; }
        public int runoutThrow { get; set; }
        public int runoutCatch { get; set; }
        public int duck { get; set; }
        public int bonusOnRunsScore { get; set; }
        public int bonusOnWickets { get; set; }
        public int totalPoints { get; set; }
        public string DreamTeamId { get; set; }
    
        public virtual DreamTeam DreamTeam { get; set; }
    }
}
