//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPLFantasy
{
    using System;
    using System.Collections.Generic;
    
    public partial class DreamTeam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DreamTeam()
        {
            this.DreamTeamPlayers = new HashSet<DreamTeamPlayer>();
        }
    
        public System.DateTime DateSubmitted { get; set; }
        public string TeamName { get; set; }
        public string Captain { get; set; }
        public string ViceCaptain { get; set; }
        public bool MoneyPaid { get; set; }
        public string DreamTeamId { get; set; }
        public int TotalScoredPoints { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DreamTeamPlayer> DreamTeamPlayers { get; set; }
        public virtual DreamTeam DreamTeams1 { get; set; }
        public virtual DreamTeam DreamTeam1 { get; set; }
    }
}
